ALTER TABLE users ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS smtp_port INTEGER DEFAULT 587;
ALTER TABLE users ADD COLUMN IF NOT EXISTS smtp_user VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS smtp_pass VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS smtp_from VARCHAR(255);
